config/routes.rb
Rails.application.routes.draw do
  root "places#index"
  resources :places
  resources :categories, only: [:index, :show]
  post "/comments", to: 'comments#create', as: 'comments'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :places
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :place
end

app/models/place.rb
class Place < ApplicationRecord
	 validates :name, presence: true
	 validates :city, inclusion: { in: %w(Ankara İstanbul Tosya),
    message: "%{value} olamaz, Sadece büyükşehirlerde mağzamız bulunabilir.." }
		has_many :comments
		belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(body: params[:body],place_id: params[:place_id])

    if @comment.save
      flash[:success] = "Başarıyla Eklendi"
      redirect_to place_path(@comment.place)
    else
      render :show
    end
  end
  def strong_params
		params.permit(:body, :place_id)
	end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

	before_action :set_place, only: [:show, :update, :edit, :destroy]

	def index
  		@places = Place.all
	end
	def show
	  @comments = Comment.new
	end
	def new
		load_categories
		@place = Place.new
	end
	def create
		@place = Place.new(strong_params)

		if @place.save
			flash[:success] = "Başarıyla Eklendi"
			redirect_to place_path(@place)
		else
			load_categories
			render :new
		end
	end
	def edit
		load_categories
	end
	def update
		if @place.update(strong_params)
			flash[:success] = "Başarıyla Güncellendi"
      redirect_to place_path(@place)
    else
			load_categories
      render :edit
    end
	end
	def destroy
		@place.destroy
		flash[:success] = "Başarıyla Silindi"
    redirect_to places_path
	end
	private

	def set_place
		@place = Place.find(params[:id])
	end
	def load_categories
		@categories = Category.all.collect {|c| [c.name, c.id]}
	end
	def strong_params
		params.require(:place).permit(:name, :address, :established_at, :phone_number, :contract_mail, :city, :description, :category_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/categories/index.html.erb
<%  flash.each do |m| %>
<%=   m[1] %>
<%  end %>
<table class="table">
	<% @categories.each do |c| %>
	<tr>
		<td><a href="<%= category_path(c) %>"><%= c.name %></a></td>
	</tr>
	<% end %>
</table>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<table class="table">
<% @category.places.each do |place| %>
  <tr>
    <td><%= place.id %></td>
    <td><%= link_to place.name, place_path(place) %></td>
    <td><%= place.description %> </td>
  </tr>
<% end %>

</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Placeproject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>
	<%= f.label 'name : ' %>
	<%= f.text_field :name, placeholder: 'title' %><br>
		<%= f.label 'Address : ' %>
	<%= f.text_field :address, placeholder: 'address' %><br>
		<%= f.label 'Established At : ' %>
	<%= f.text_field :established_at %><br>
		<%= f.label 'Phone Number : ' %>
	<%= f.text_field :phone_number, placeholder: 'phone_number' %><br>
		<%= f.label 'Mail : ' %>
	<%= f.text_field :contract_mail, placeholder: 'contract_mail' %><br>
		<%= f.label 'City : ' %>
	<%= f.text_field :city, placeholder: 'city' %><br>
		<%= f.label 'Description : ' %>
	<%= f.text_field :description, placeholder: 'description' %><br>
		<%= f.label 'Kategori : ' %>
	<%= f.select :category_id, @categories %><br>

	<%= f.submit 'Gonder'%><br>
<% end %>

app/views/places/edit.html.erb
<%  flash.each do |m| %>
<%=   m[1] %>
<%  end %>
<h1>Edit a place</h1>
<% if @place.errors.any? %>
<%=  	@place.errors.full_messages.join(",") %><br>
<% end %>
<%= render 'form' %>

app/views/places/index.html.erb
<%  flash.each do |m| %>
<%=   m[1] %>
<%  end %>
<table class="table">
	<% @places.each do |p| %>
	<tr>
		<td><a href="<%= place_path(p) %>"><%= p.name %></a></td>
		<td><%= p.address %></td>
		<td><%= p.established_at %></td>
		<td><%= p.phone_number %></td>
		<td><%= p.contract_mail %></td>
		<td><%= p.city %></td>
		<td><%= p.description %></td>
	</tr>
	<% end %>
</table>

app/views/places/new.html.erb
<%  flash.each do |m| %>
<%=   m[1] %>
<%  end %>
<h1>Create new place</h1>

<% if @place.errors.any? %>
<%=  	@place.errors.full_messages.join(",") %><br>
<% end %>
<%= render 'form' %>

app/views/places/show.html.erb
<h1>Burası  Show</h1>
<%  flash.each do |m| %>
<%=   m[1] %>
<%  end %>
<table class="table">
	<tr>
		<td><%= @place.id %></td>
		<td><%= @place.name %></td>
		<td><%= @place.address %></td>
		<td><%= @place.established_at %></td>
		<td><%= @place.phone_number %></td>
		<td><%= @place.contract_mail %></td>
		<td><%= @place.city %></td>
		<td><%= @place.description %></td>
		<td><%= link_to "Güncelle", edit_place_path(@place) %></td>
		<td><%= link_to "Sil", place_path(@place), method: :delete %></td>
	</tr>
</table>
<h4>Yorumlar</h4><hr>
<% @place.comments.each do |e| %>
<%=	e.body %><br>
<% end %>
<h4>Yorum Yap</h4><hr>


<form action="<%= comments_path %>" method="post">
	<textarea name="body" rows="8" cols="40"></textarea>
	<input type="hidden" name="place_id" value="<%= @place.id %>">
	<input type="submit" name="name" value="Gonder">
</form>